In [1]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.1.3


# TASK1-Creating NumPy Arrays

In [2]:
#code example
import numpy as np

# Python list
marks_list = [45, 60, 72, 88]

# Convert to NumPy array
marks_array = np.array(marks_list)

print("List:", marks_list)
print("Array:", marks_array)
print("Type of list:", type(marks_list))
print("Type of array:", type(marks_array))


List: [45, 60, 72, 88]
Array: [45 60 72 88]
Type of list: <class 'list'>
Type of array: <class 'numpy.ndarray'>


# TASK1A- LIST OF TEMPERATURE IN CELSIUS 

In [3]:
import numpy as np

# Temperature list
temp_list = [22, 25, 28, 30, 27]

# Convert to NumPy array
temp_array = np.array(temp_list)

print("Temperature List:", temp_list)
print("Temperature Array:", temp_array)
print("Type:", type(temp_array))


Temperature List: [22, 25, 28, 30, 27]
Temperature Array: [22 25 28 30 27]
Type: <class 'numpy.ndarray'>


# TASK1B-Using np.arange and np.linspace

In [5]:
# CODE EXAMPLE 
# np.arange(start, stop, step)
a = np.arange(0, 10, 2)
print("arange array:", a)

# np.linspace(start, stop, num_of_values)
b = np.linspace(0, 1, 5)
print("linspace array:", b)

arange array: [0 2 4 6 8]
linspace array: [0.   0.25 0.5  0.75 1.  ]


In [8]:
range_arr = np.linspace(5, 10, 6)
print("6 Values Between 5 and 10:", range_arr)

6 Values Between 5 and 10: [ 5.  6.  7.  8.  9. 10.]


In [9]:
even_arr = np.arange(2, 21, 2)
print("Even Numbers:", even_arr)

Even Numbers: [ 2  4  6  8 10 12 14 16 18 20]


# TASK1C-Zeros, Ones and Random Arrays

In [7]:
zeros_arr = np.zeros((3, 3))     # 3x3 matrix of zeros
ones_arr  = np.ones((2, 4))      # 2x4 matrix of ones
rand_arr  = np.random.rand(2, 3) # 2x3 matrix of random numbers (0 to 1)

print("Zeros:\n", zeros_arr)
print("Ones:\n", ones_arr)
print("Random:\n", rand_arr)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Random:
 [[0.55931341 0.3582267  0.16875874]
 [0.67131612 0.81439433 0.91846898]]


In [10]:
zeros_arr = np.zeros((4, 4))
print("4x4 Zeros Array:\n", zeros_arr)

4x4 Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones_arr = np.ones((3, 2))
print("3x2 Ones Array:\n", ones_arr)

3x2 Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
rand_arr = np.random.rand(5)
print("Random 5 Element Array:\n", rand_arr)

Random 5 Element Array:
 [0.14944958 0.63662239 0.88960114 0.39677659 0.76514266]


# Part 3A – 1D Indexing & Slicing

In [13]:
a = np.array([5, 10, 15, 20, 25, 30])
print("First element:", a[0])
print("Last two elements:", a[-2:])
print("Every second element:", a[::2])
print("a[1:4] =", a[1:4])


First element: 5
Last two elements: [25 30]
Every second element: [ 5 15 25]
a[1:4] = [10 15 20]


In [14]:
# Part 3B – 2D Indexing
mat = np.array([
[10, 20, 30, 40],
[50, 60, 70, 80],
[90, 100, 110, 120]
])


print("Element row 2, col 1:", mat[2, 1])
print("Second row:", mat[1, :])
print("Last column:", mat[:, -1])
print("Sub-matrix (first 2 rows, first 3 columns):\n", mat[0:2, 0:3])

Element row 2, col 1: 100
Second row: [50 60 70 80]
Last column: [ 40  80 120]
Sub-matrix (first 2 rows, first 3 columns):
 [[10 20 30]
 [50 60 70]]


# Part 4A – Scalar Arithmetic

In [15]:
marks = np.array([40, 55, 63, 72, 90])
print("Marks + 5 bonus:", marks + 5)
print("Marks / 100:", marks / 100)

Marks + 5 bonus: [45 60 68 77 95]
Marks / 100: [0.4  0.55 0.63 0.72 0.9 ]


In [16]:
# Part 4B – Element-wise Operations
x = np.array([2, 4, 6, 8])
y = np.array([1, 3, 5, 7])
print("x + y =", x + y)
print("x - y =", x - y)
print("x * y =", x * y)


# Part 4C – Basic Statistics
arr = np.random.randint(0, 101, size=8)
print("Array:", arr)
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Mean:", np.mean(arr))

x + y = [ 3  7 11 15]
x - y = [1 1 1 1]
x * y = [ 2 12 30 56]
Array: [84 88 97 50 15 69  3 70]
Min: 3
Max: 97
Mean: 59.5


# Part 5 – Mini Data Cleaning Exercise

In [17]:
values = np.array([15, 16, 200, 17, 16, 400, 15, 18, 1])
print("Original values:", values)


mean_val = np.mean(values)
std_val = np.std(values)
print("Mean:", mean_val)
print("Std:", std_val)


cleaned = np.where((values > 50) | (values < 5), mean_val, values)
print("Cleaned values:", cleaned)


# Home Task
matrix = np.array([
[85, 90, 75, 88],
[70, 65, 80, 72],
[92, 88, 95, 90],
[60, 55, 70, 65]
])

Original values: [ 15  16 200  17  16 400  15  18   1]
Mean: 77.55555555555556
Std: 127.99401992203569
Cleaned values: [15.         16.         77.55555556 17.         16.         77.55555556
 15.         18.         77.55555556]
